#!/usr/bin/env php
<?php

use Contao\PackageList\Kernel;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Dotenv\Dotenv;

set_time_limit(0);

$loader = require __DIR__.'/../vendor/autoload.php';

new Dotenv()->loadEnv(__DIR__.'/../.env', overrideExistingVars: true);

$kernel = new Kernel($_ENV['APP_ENV'] ?? 'prod', 'dev' === ($_ENV['APP_ENV'] ?? 'prod'));
new Application($kernel)->run();
